;; (global-set-key [(control f3)] 'highlight-symbol-at-point)
;; (global-set-key (kbd "C-<SPC>") 'avy-goto-char)
(spacemacs/set-leader-keys "hh" 'highlight-symbol-at-point)
(spacemacs/set-leader-keys "hH" 'highlight-symbol-remove-all)
;; (spacemacs/set-leader-keys "g C-s" 'svn-global-keymap)
